name: Test

on: [push, pull_request, workflow_dispatch]

permissions: write-all

env:
  MSYS2_ARG_CONV_EXCL: "*"
  MSYS_NO_PATHCONV: 1
 
jobs:
  testAllModes:
    name: Test in ${{ matrix.testMode }}
    runs-on: self-hosted
    timeout-minutes: 45
    env:
      ACTIONS_CACHE_USE_AZURE_CLI: false
      ACTIONS_CACHE_UPLOAD_CHUNK_SIZE: 32000000
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - .
        testMode:
          - editmode
        unityVersion:
          - 6000.2.6f2
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true
 
      - name: Debug directory structure
        shell: powershell
        run: |
          echo "Workflow Directory:"
          pwd
          echo "Root Directory:"
          Get-ChildItem -Force
          echo "ProjectSettings:"
          Get-ChildItem -Force ${{ matrix.projectPath }}/ProjectSettings

      - uses: actions/cache@v5
        with:
          path: ${{ github.workspace }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.unityVersion }}-v2
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.unityVersion }}-
            Library-${{ matrix.projectPath }}-
            Library-

      - name: Run EditMode Tests
        shell: powershell
        env:
          UNITY_PATH: ${{ secrets.UNITY_PATH }}
        run: |
          $resultsPath = ".\editmode-artifacts\results.xml"
          New-Item -ItemType Directory -Force -Path ".\editmode-artifacts"
          Start-Process -FilePath "$env:UNITY_PATH" -ArgumentList "-runTests", "-testPlatform", "${{ matrix.testMode }}", "-projectPath", ".", "-testResults", $resultsPath, "-batchmode", "-nographics" -Wait -NoNewWindow
          Write-Host "Test results path: $(Resolve-Path .\editmode-artifacts -ErrorAction SilentlyContinue)"
          exit $LASTEXITCODE

      - uses: actions/upload-artifact@v6
        if: always()
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ github.workspace }}\${{ matrix.testMode }}-artifacts